name: CI Check

# This workflow runs on all pull requests targeting master, 
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'npm' # Automatically caches ~/.npm to speed up future runs

      - name: Install dependencies
        # npm ci is strictly better than npm install in CI environments 
        # as it relies exactly on your package-lock.json and fails if it's out of sync.
        run: npm ci

      - name: Run Linter
        # Assumes you have a "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0" script
        run: npm run check-ci

      - name: Type Check
        # Vite's build command usually runs tsc, but running it separately here 
        # gives you clearer, isolated error messages if there's a TypeScript violation.
        run: npx tsc --noEmit

      - name: Test Project
        # Verifies that all tests passes
        run: npm run test

      - name: Build Project
        # Verifies that Vite can successfully bundle the application
        run: npm run build
